---
title: "Gesture-Speech Model Simulations"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r load-libraries}
library(tidyverse)
library(tidyboot)
library(DescTools)
library(here)
library(glue)

theme_set(theme_few(base_size = 14))

```

```{r teaching}
teach_learn_p <- function(p , n) {
  1 - (1-p) ^ n
}

teach_learn_prop <- function(p) {
  tibble(n = 1:100, prob = map(1:100, ~teach_learn_p(p, .x)) 
         %>% unlist()) %>%
    mutate(p = p)
}
```

```{r teaching_cache, eval = F}
teach_props <- map_df(seq(.1, 1, .1), ~teach_learn_prop(.x)) %>%
  mutate(p = as.numeric(as.character(p))) %>%
    rename(trial = n)

teach_aucs <- teach_props %>%
  group_by(p) %>%
  summarise(auc = AUC(trial, prob))

write_csv(teach_props, here("cached_data/teach_props.csv"))
write_csv(teach_aucs, here("cached_data/teach_aucs.csv"))
```

personalized communication
```{r setup-communication} 
U <- 100
EPSILON <- .001

DEFAULT_P <- 70
DEFAULT_S <- 0
DEFAULT_ALPHA <-2
DEFAULT_LAMBDA <- .5


p <- .6

teach_outcome <- function(n = 1, p = .6) {
  1 - (1-p) ^ n
}

# this can't contain ps if it's going to get logged
speak_success_u <- function(S = 0) {
 log(max(U - S, 0) + EPSILON)
}

speak_fail_u <- function(S) {
 log(max(0 - S, EPSILON))
}

point_u <- function(P = 30) {
  log(max(U - P, 0) + EPSILON)
}

teach_u <- function(P = 30, S = 0) {
  log(max(U - P - S, 0) + EPSILON)
}

discount <- function(delay, lambda = .5) {
  lambda ^ delay
}

act_u <- function(delay, k, n, p = .6, P = DEFAULT_P, S = DEFAULT_S, 
                  alpha = DEFAULT_ALPHA, lambda = DEFAULT_LAMBDA) {
  
  if(delay > MAX_DELAY) {
    expected_util <- 0
    teach_p <- NA
    speak_p <- NA
  }
  
  else {
    if(k == 0) {
      
      speak_util <- speak_fail_u(S) +
        discount(delay + 1, lambda) * 
        (act_u(delay + 1, k = 0, n = 0, p, P, S, 
               alpha, lambda) %>% pull(eu))
      
      point_util <- point_u(P) + 
        discount(delay + 1, lambda) * 
        (act_u(delay + 1, k = 0, n = 0, p, P, S, 
               alpha, lambda) %>% pull(eu))
      
      #teach_outcome(1, p) instead of 1
      teach_util <- teach_u(P, S) + 
        discount(delay + 1, lambda) * 
        (act_u(delay + 1, k = 1, n = 1, p, P, S, 
               alpha, lambda) %>% pull(eu))
      
    } else if(k == 1) {
       speak_util <- speak_success_u(S) + 
                       discount(delay + 1, lambda) * 
                       (act_u(delay + 1, k = 1, n = 0, p, P, S, 
                              alpha, lambda) %>% pull(eu))

       point_util <- point_u(P) + 
                       discount(delay + 1, lambda) * 
                       (act_u(delay + 1, k = 1, n = 0, p, P, S, 
                              alpha, lambda) %>% pull(eu))
       
       teach_util <- teach_u(P, S) + 
         discount(delay + 1, lambda) * 
         (act_u(delay + 1, k = 1, n = n + 1, p, P, S, alpha, lambda) %>%
            pull(eu))
      
    } else {
      speak_util <- (k * (speak_success_u(S) +
                           discount(delay + 1, lambda) * 
                           (act_u(delay + 1, k = 1, n = 0, p, P, S, 
                                  alpha, lambda) 
                            %>% pull(eu)))) +
        ((1-k) * (speak_fail_u(S) + discount(delay+1, lambda) * 
                       (act_u(delay + 1, k = 0, n = 0, p, P, S, 
                              alpha, lambda) %>% pull(eu))))
      
      point_util <- point_u(P) + discount(delay + 1, lambda) * 
         (act_u(delay + 1, k, n, p, P, S, alpha, lambda) %>% pull(eu))
            
      # teach_outcome(n + 1, p) instead of 1
      teach_util <- teach_u(P, S) + discount(delay + 1, lambda) * 
         (act_u(delay + 1, k = 1, n = n + 1, p, P, S, 
                alpha, lambda) 
          %>% pull(eu))
    }
   
   teach_p <- exp(alpha * teach_util) / (
     exp(alpha * teach_util) + (exp(alpha * speak_util) + 
                                  (exp(alpha * point_util))))
   
   speak_p <- exp(alpha * speak_util) / (
     exp(alpha * speak_util) + (exp(alpha * point_util) + 
                                  (exp(alpha * teach_util))))
   
   expected_util <- teach_p * teach_util + (speak_p) * speak_util +
     (1 - speak_p - teach_p) * point_util
  
#  print(expected_util)
  }
   
   tibble(delay = delay,
          n = n,
          eu = expected_util,
          pspeak = speak_p,
          ppoint = 1 - speak_p - teach_p,
          pteach = teach_p, 
          P = P,
          S = S,
          alpha = alpha,
          lambda = lambda)
   
}
```


```{r simulate-communocation}
MAX_DELAY <- 3
MAX_TRIAL <- 100

communication_probs <- function(p, P = DEFAULT_P, S = DEFAULT_S, 
                                alpha = DEFAULT_ALPHA, lambda = DEFAULT_LAMBDA) {

  teach_probs <- map_df(0:MAX_TRIAL, ~act_u(delay = 0, teach_outcome(.x, p), 
                                     n = .x, p, P = P, S = S, 
                                     alpha = alpha, lambda = lambda)) %>%
    select(-delay, -eu) #%>%
   # mutate(know_prob =  teach_outcome(n + 1, p = p))
  
  
  teach_counts <- tibble(n = 0, prob = 1)
  

  unknown_remaining <- function(trials, unknowns, teach_counts) {
    
    trial = last(trials)
    unknown = last(unknowns)
    
    if(trial == MAX_TRIAL)
      return(tibble(trial = trials, prob = 1 - unknowns))
    
    updated_counts <- teach_counts %>%
      left_join(teach_probs, by = "n") %>%
      gather(modality, outcome, pspeak, ppoint, pteach) %>%
      mutate(new_prob = prob * outcome)
    
    taught <- updated_counts %>% 
      filter(modality == "pteach") %>% 
      mutate(new_prob = new_prob * p) %>%
      summarise(new_prob = sum(new_prob)) %>%
      pull()
      
    
    unknown <- unknown * (1 - taught)
    
    teach_counts <- updated_counts %>%
      mutate(new_prob = if_else(modality == "pteach",
                               new_prob * (1 - p), new_prob),
             n = if_else(modality == "pspeak", 0,
                         if_else(modality == "pteach", n + 1, n))) %>%
      select(-outcome, -modality, -prob) %>%
      group_by(n) %>%
      rename(prob = new_prob) %>%
      summarise(prob = sum(prob)) %>%
      mutate(prob = prob / sum(prob))
    
    return(unknown_remaining(c(trials, trial + 1), 
                             c(unknowns, unknown),
                             teach_counts))
  }

unknown_remaining(0, 1, teach_counts) %>%
  mutate(p = p,
         P = P,
         S = S,
         alpha = alpha,
         lambda = lambda)
}
```

```{r cache-communication}
#.1 and, 10, .5, .2 steps
combos <- expand_grid(p = seq(.1, 1, .1), P = c(70,50,60,80), 
                      S = c(0,10,20,30), alpha = seq(.5, 3, .5),
                      lambda = seq(.1, 1, .1)) %>%
  filter(P > S, (P + S) <= 100) %>%
  filter(!(P == 50 & S %in% c(0,20)), !(P == 70 & S %in% c(0,20)))
  as_tibble() 


com_props <- map_df(1:nrow(combos), 
                    ~communication_probs(combos %>% slice(.x) %>% pull(p), 
                                         combos %>% slice(.x) %>% pull(P),
                                         combos %>% slice(.x) %>% pull(S),
                                         combos %>% slice(.x) %>% pull(alpha),
                                         combos %>% slice(.x) %>% 
                                           pull(lambda))) %>%
  mutate(p = as.numeric(as.character(p)),
         lambda = as.numeric(as.character(lambda)))

com_props2 <- read_csv(here("cached_data/com_props_newmodel.csv"))


join_com_props <- com_props2 %>% 
  bind_rows(com_props)

com_aucs <- join_com_props %>%
  filter(trial != 0) %>%
  group_by(p, P, S) %>%
  summarise(auc = AUC(trial, prob))

write_csv(join_com_props, here("cached_data/join_com_props.csv"))
write_csv(com_aucs, here("cached_data/join_com_aucs.csv"))
```

```{r propose-but-verify}
generate_propose_stims <- function(C = 4, M = 16, n = 100) {
  replicate(n, enframe(sample(2:M, C - 1)), simplify = F) %>%
    bind_rows(.id = "trial") %>%
    select(-name) %>%
    rename(object = value) %>%
    mutate(trial = as.numeric(trial)) %>%
    bind_rows(tibble(trial = 1:n, object = 1))
}

propose_but_verify <- function(p = .6, C = 4, M = 16, n = 100, 
                                        nguesses = 4) {
  stims <- generate_propose_stims(C, M, n)
  
  guesses <- 0
  trial <- 0
  
  for(i in 1:n) {
    
    if(length(guesses) == 1 && guesses == 1) {
      trial <- i
      break
    }
    
    trial_stims <- stims %>%
      filter(trial == i) %>%
      pull(object)
    
    matches <- intersect(guesses, trial_stims)
    
    if(is_empty(matches)) {
      selected <- sample(trial_stims, min(nguesses, length(trial_stims)))
      
      kept <- selected[as.logical(rbinom(length(selected), 1, p))]
                         
      if(is_empty(kept))
        guesses <- 0
      else
        guesses <- kept
    } else {
      guesses <- matches
    }
    
  }
  
  return(trial)
}


pbv_samples <- function(reps = 1000, p = .6, C = 4, M = 16, n = 100, 
                        nguesses = 1) {
  print(glue("p = {p}, C = {C}, M = {M}, nguesses = {nguesses}"))
  replicate(reps, propose_but_verify(p, C, M, n, nguesses)) %>%
    enframe() %>%
    select(-name) %>%
    mutate(p = p, C = C, M = M, nguesses = nguesses) %>%
    rename(n = value)
}
```

```{r pbv_cache}
pbv_combos <- expand_grid(p = seq(.1, 1, .1), C = c(1, 2, 4, 8), 
                          nguesses = c(1, 2, 3, 4), 
                          M = c(8, 16, 32, 64, 128)) %>%
  filter(nguesses <= C) 
     
pbv_props <- map_df(1:nrow(pbv_combos), 
                    ~pbv_samples(p = pbv_combos %>% slice(.x) %>% pull(p), 
                                 C = pbv_combos %>% slice(.x) %>% pull(C),
                                 M = pbv_combos %>% slice(.x) %>% pull(M),
                                 nguesses = pbv_combos %>% slice(.x) %>%
                                   pull(nguesses))) %>%
  mutate(p = as.numeric(as.character(p))) %>%
  group_by(M, C, nguesses, p, n) %>%
  summarise(prob = n()) %>%
  complete(n = full_seq(1:100, 1), p, M, C, nguesses, fill = list(prob =0)) %>%
  arrange(M, C, nguesses, p, n) %>%
  mutate(prob = prob/sum(prob),
         prob = cumsum(prob)) %>%
  rename(trial = n)


pbv_aucs <- pbv_props %>%
  group_by(M, C, nguesses, p) %>%
  summarise(auc = AUC(trial, prob))

write_csv(pbv_props, here("cached_data/pbv_props.csv"))
write_csv(pbv_aucs, here("cached_data/pbv_aucs.csv"))
```

```{r plot}
all_props <- communication_props %>%
  mutate(type = "communication") %>% 
  rename(n = trial) %>%
  bind_rows(mutate(teach_props, type = "teaching")) %>%
#  bind_rows(mutate(cross_props, type = "xsit")) %>%
  bind_rows(mutate(pbv_props, type = "pbv")) %>%
  mutate(type = factor(type, levels = c("teaching", "communication", 
                                         "pbv")))


ggplot(all_props, aes(x = n, y = prob, color = as.factor(p))) + 
  geom_line(aes(linetype = type)) + 
  scale_color_brewer(palette = "Set1")

```

